#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IO-stringy
Version  : 2.111
Release  : 2
URL      : http://search.cpan.org/CPAN/authors/id/D/DS/DSKOLL/IO-stringy-2.111.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/D/DS/DSKOLL/IO-stringy-2.111.tar.gz
Summary  : ~
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-IO-stringy-doc

%description
NAME
IO-stringy - I/O on in-core objects like strings and arrays
SYNOPSIS
IO::
::AtomicFile   adpO  Write a file which is updated atomically     ERYQ
::Lines        bdpO  I/O handle to read/write to array of lines   ERYQ
::Scalar       RdpO  I/O handle to read/write to a string         ERYQ
::ScalarArray  RdpO  I/O handle to read/write to array of scalars ERYQ
::Wrap         RdpO  Wrap old-style FHs in standard OO interface  ERYQ
::WrapTie      adpO  Tie your handles & retain full OO interface  ERYQ

%package doc
Summary: doc components for the perl-IO-stringy package.
Group: Documentation

%description doc
doc components for the perl-IO-stringy package.


%prep
%setup -q -n IO-stringy-2.111

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/IO/AtomicFile.pm
/usr/lib/perl5/site_perl/5.26.1/IO/InnerFile.pm
/usr/lib/perl5/site_perl/5.26.1/IO/Lines.pm
/usr/lib/perl5/site_perl/5.26.1/IO/Scalar.pm
/usr/lib/perl5/site_perl/5.26.1/IO/ScalarArray.pm
/usr/lib/perl5/site_perl/5.26.1/IO/Stringy.pm
/usr/lib/perl5/site_perl/5.26.1/IO/Wrap.pm
/usr/lib/perl5/site_perl/5.26.1/IO/WrapTie.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
